// Code generated by mockery v2.31.4. DO NOT EDIT.

package p2p

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockAnnouncer is an autogenerated mock type for the Announcer type
type MockAnnouncer struct {
	mock.Mock
}

type MockAnnouncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnnouncer) EXPECT() *MockAnnouncer_Expecter {
	return &MockAnnouncer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: req
func (_m *MockAnnouncer) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockAnnouncer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockAnnouncer_Expecter) Do(req interface{}) *MockAnnouncer_Do_Call {
	return &MockAnnouncer_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockAnnouncer_Do_Call) Run(run func(req *http.Request)) *MockAnnouncer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockAnnouncer_Do_Call) Return(_a0 *http.Response, _a1 error) *MockAnnouncer_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncer_Do_Call) RunAndReturn(run func(*http.Request) (*http.Response, error)) *MockAnnouncer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnnouncer creates a new instance of MockAnnouncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnnouncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnnouncer {
	mock := &MockAnnouncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
